Added contributors page
virtual-labs/ph3-lab-mgmt pull request #80
Opened 2022-10-21 08:50 UTC by shreyash-x

2022-10-21 08:54 UTC, shreyash-x commented
Resolved conflicts with master as well

2022-10-21 12:24 UTC, raj-vlabs requested changes

2022-10-28 06:12 UTC, shreyash-x commented on Experiment.js
> +      bp : Config.build_path(this.src) + "/",
Done

2022-10-28 06:12 UTC, shreyash-x commented on Experiment.js
> +    const contributorsLU = {
Done

2022-10-28 06:17 UTC, raj-vlabs approved these changes

2022-10-28 06:17 UTC, merged